### ISSUE TITLE
Support NOT LIKE operator

### ISSUE THREAD

**Issue by Raidus** [magoo-magoo/keyrier-json#349]
Hi,

very cool tool! 

Would be great if you are planning to implement a `NOT LIKE` operator. For example:

`select * from data where eyeColor NOT LIKE '%l%'`

**Comment by magoo-magoo** [comment]
Hello,
Thank you for your feedback!
I'll try to do it when possible.

**Comment by magoo-magoo** [comment]
Finally implemented!
